### ISSUE TITLE
Create a blog post to communicate the progress in the r2d JHub service project (GESIS)

### ISSUE THREAD

**Issue by damianavila** [2i2c-org/2i2c-brochure#118]
### Context

Goal: Write down things we have done so far publicly so it is visible to external stakeholders.

### Proposal

* Create a blog post at https://2i2c.org/blog/
* Before Nov 9th
* Invite Arnim to provide comments (GESIS point of view)
* Make sure we discuss the importance of launch links

**Comment by arnim** [comment]
Thank you @damianavila  :) 

I will also discuss with @schochastics if it makes sense to do a corresponding post on https://blog.gesis.org

**Comment by arnim** [comment]
This blog post is is about work done in of 2i2c-org/infrastructure/issues/1382

**Comment by arnim** [comment]
This might be also interesting to @berndflemisch and @aseeland. They are leading the [NFDI-Jupyter](https://github.com/NFDI-Jupyter) working group.

**Comment by choldgraf** [comment]
I've gone through and made a few comments and edits throughout! I think that it in general it is a nice update for the community. In particular I would love if we could find more ways to invite participation and feedback from others, or identify people that could help us conduct UI/UX research.

**Comment by arnim** [comment]
Thank you @choldgraf :)
Some other things popped up and we had to push this 1 week back anyways ...

**Comment by damianavila** [comment]
This is the [first draft of the blog post](https://docs.google.com/document/d/1EL30A5ouTgn_vuWfwiqu5qgb-hTbJqoFR0MpmSgLzqI/edit#heading=h.2g10egwm8o1g) (shared with you gmail account, @arnim).

It is mostly centered on a descriptive view of the collaboration and the steps we have completed so far.
It also has some new information/links I plan to discuss with you later this week in our recurring meeting.

Feel free to suggest changes, @arnim!

**Comment by arnim** [comment]
To meet our DFG [guidelines](https://www.dfg.de/formulare/2_012e/2_012e.pdf) for the use of funds we should add to the post

> Funded by the German Research Foundation (DFG), [CESSDA](http://www.cessda.eu), and [GESIS](http://gesis.org).
FKZ/project number:[460234259](https://gepris.dfg.de/gepris/projekt/460234259?language=en).

**Comment by arnim** [comment]
The blog post should provide a bird's-eye perspective on the project and serve as an entry point to further resources on how to integrate with the created software. The main way for integration with this software is via binder style build- / launch- / import-badges . Given a [binder-example repository](https://github.com/binder-examples/requirements) we currently follow the established schema 

> http://example-jhub.base/services/binder/v2/gh/binder-examples/requirements/master

to build / launch / import the repository. We may be able to change the mechanism. Since others rely on this API we should ensure that this is communicated as transparent as possible and that all are fine with the changes if changes to this mechanism are necessary. Since the blog post should give only a ~500 words overview, it may be best to link to an issue from the blog post.  

What do you think @damianavila?
